liTest run started
liTest scala.scalanative.junit.ExceptionAfterAssume.assumeFail started
leTest scala.scalanative.junit.ExceptionAfterAssume.assumeFail failed: This assume should not pass, took <TIME>
e2scala.scalanative.junit.ExceptionAfterAssume.assumeFail
leTest scala.scalanative.junit.ExceptionAfterAssume.assumeFail failed: after() must be called, took <TIME>
ldTest scala.scalanative.junit.ExceptionAfterAssume.assumeFail finished, took <TIME>
liTest run finished: 2 failed, 0 ignored, 1 total, <TIME>
d
